<a href="https://colab.research.google.com/github/Kiduhu/Kiduhu/blob/main/Churn_prediction_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Feature Engineering and Modelling

---

1. Import packages
2. Load data
3. Modelling

---

## 1. Import packages

In [34]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn import metrics

Load data

In [13]:
df=pd.read_csv('/content/data_for_predictions.csv')
df.head()

   Unnamed: 0  ... origin_up_lxidpiddsbxsbosboudacockeimpuepw
0           0  ...                                          1
1           1  ...                                          0
2           2  ...                                          0
3           3  ...                                          0
4           4  ...                                          0

[5 rows x 64 columns]

In [14]:
import warnings
warnings.filterwarnings('ignore', category=FutureWarning)

In [15]:
df.drop(columns=["Unnamed: 0"],inplace=True)
df.head()

                                 id  ...  origin_up_lxidpiddsbxsbosboudacockeimpuepw
0  24011ae4ebbe3035111d65fa7c15bc57  ...                                           1
1  d29c2c54acc38ff3c0614d0a653813dd  ...                                           0
2  764c75f661154dac3a6c254cd082ea7d  ...                                           0
3  bba03439a292a1e166f80264c16191cb  ...                                           0
4  149d57cf92fc41cf94415803a877cb4b  ...                                           0

[5 rows x 63 columns]

In [17]:
df.shape

(14606, 63)

Check missing values

In [18]:
df.isnull().sum()

id                                            0
cons_12m                                      0
cons_gas_12m                                  0
cons_last_month                               0
forecast_cons_12m                             0
                                             ..
channel_lmkebamcaaclubfxadlmueccxoimlema      0
channel_usilxuppasemubllopkaafesmlibmsdf      0
origin_up_kamkkxfxxuwbdslkwifmmcsiusiuosws    0
origin_up_ldkssxwpmemidmecebumciepifcamkci    0
origin_up_lxidpiddsbxsbosboudacockeimpuepw    0
Length: 63, dtype: int64

In [19]:
df.describe()

           cons_12m  ...  origin_up_lxidpiddsbxsbosboudacockeimpuepw
count  14606.000000  ...                                14606.000000
mean       4.223939  ...                                    0.485896
std        0.884515  ...                                    0.499818
min        0.000000  ...                                    0.000000
25%        3.754023  ...                                    0.000000
50%        4.149727  ...                                    0.000000
75%        4.610285  ...                                    1.000000
max        6.792889  ...                                    1.000000

[8 rows x 62 columns]

In [21]:
df.columns

Index(['id', 'cons_12m', 'cons_gas_12m', 'cons_last_month',
       'forecast_cons_12m', 'forecast_discount_energy',
       'forecast_meter_rent_12m', 'forecast_price_energy_off_peak',
       'forecast_price_energy_peak', 'forecast_price_pow_off_peak', 'has_gas',
       'imp_cons', 'margin_gross_pow_ele', 'margin_net_pow_ele', 'nb_prod_act',
       'net_margin', 'pow_max', 'var_year_price_off_peak_var',
       'var_year_price_peak_var', 'var_year_price_mid_peak_var',
       'var_year_price_off_peak_fix', 'var_year_price_peak_fix',
       'var_year_price_mid_peak_fix', 'var_year_price_off_peak',
       'var_year_price_peak', 'var_year_price_mid_peak',
       'var_6m_price_off_peak_var', 'var_6m_price_peak_var',
       'var_6m_price_mid_peak_var', 'var_6m_price_off_peak_fix',
       'var_6m_price_peak_fix', 'var_6m_price_mid_peak_fix',
       'var_6m_price_off_peak', 'var_6m_price_peak', 'var_6m_price_mid_peak',
       'churn', 'offpeak_diff_dec_january_energy',
       'offpeak_diff_dec_january_power', 'off_peak_peak_var_mean_diff',
       'peak_mid_peak_var_mean_diff', 'off_peak_mid_peak_var_mean_diff',
       'off_peak_peak_fix_mean_diff', 'peak_mid_peak_fix_mean_diff',
       'off_peak_mid_peak_fix_mean_diff', 'off_peak_peak_var_max_monthly_diff',
       'peak_mid_peak_var_max_monthly_diff',
       'off_peak_mid_peak_var_max_monthly_diff',
       'off_peak_peak_fix_max_monthly_diff',
       'peak_mid_peak_fix_max_monthly_diff',
       'off_peak_mid_peak_fix_max_monthly_diff', 'tenure', 'months_activ',
       'months_to_end', 'months_modif_prod', 'months_renewal',
       'channel_MISSING', 'channel_ewpakwlliwisiwduibdlfmalxowmwpci',
       'channel_foosdfpfkusacimwkcsosbicdxkicaua',
       'channel_lmkebamcaaclubfxadlmueccxoimlema',
       'channel_usilxuppasemubllopkaafesmlibmsdf',
       'origin_up_kamkkxfxxuwbdslkwifmmcsiusiuosws',
       'origin_up_ldkssxwpmemidmecebumciepifcamkci',
       'origin_up_lxidpiddsbxsbosboudacockeimpuepw'],
      dtype='object')

---

## 3. Modelling

We now have a dataset containing features that we have engineered and we are ready to start training a predictive model. Remember, we only need to focus on training a `Random Forest` classifier.

### Data sampling

The first thing we want to do is split our dataset into training and test samples. The reason why we do this, is so that we can simulate a real life situation by generating predictions for our test sample, without showing the predictive model these data points. This gives us the ability to see how well our model is able to generalise to new data, which is critical.

A typical % to dedicate to testing is between 20-30, for this example we will use a 75-25% split between train and test respectively.

In [24]:
## Make a copy of our data
train_df=df.copy()

In [26]:
x=df.drop(columns=['id','churn'])
y=df['churn']

In [27]:
print(x.shape)
print(y.shape)

(14606, 61)
(14606,)

In [28]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(10954, 61)
(3652, 61)
(10954,)
(3652,)

### Model training

Once again, we are using a `Random Forest` classifier in this example. A Random Forest sits within the category of `ensemble` algorithms because internally the `Forest` refers to a collection of `Decision Trees` which are tree-based learning algorithms. As the data scientist, you can control how large the forest is (that is, how many decision trees you want to include).

The reason why an `ensemble` algorithm is powerful is because of the laws of averaging, weak learners and the central limit theorem. If we take a single decision tree and give it a sample of data and some parameters, it will learn patterns from the data. It may be overfit or it may be underfit, but that is now our only hope, that single algorithm.

With `ensemble` methods, instead of banking on 1 single trained model, we can train 1000's of decision trees, all using different splits of the data and learning different patterns. It would be like asking 1000 people to all learn how to code. You would end up with 1000 people with different answers, methods and styles! The weak learner notion applies here too, it has been found that if you train your learners not to overfit, but to learn weak patterns within the data and you have a lot of these weak learners, together they come together to form a highly predictive pool of knowledge! This is a real life application of many brains are better than 1.

Now instead of relying on 1 single decision tree for prediction, the random forest puts it to the overall views of the entire collection of decision trees. Some ensemble algorithms using a voting approach to decide which prediction is best, others using averaging.

As we increase the number of learners, the idea is that the random forest's performance should converge to its best possible solution.

Some additional advantages of the random forest classifier include:

- The random forest uses a rule-based approach instead of a distance calculation and so features do not need to be scaled
- It is able to handle non-linear parameters better than linear based models

On the flip side, some disadvantages of the random forest classifier include:

- The computational power needed to train a random forest on a large dataset is high, since we need to build a whole ensemble of estimators.
- Training time can be longer due to the increased complexity and size of thee ensemble

In [29]:
model=RandomForestClassifier()
#Train the model
model.fit(x_train,y_train)

RandomForestClassifier()

In [35]:
# model evaluation
x_test_pred=model.predict(x_test)
test_data_accuracy=accuracy_score(x_test_pred,y_test)
print('Accuracy: ',test_data_accuracy)

Accuracy:  0.9041621029572837

In [38]:
# Generate classification report and confusion matrix
print("\nClassification Report:")
print(metrics.classification_report(y_test, x_test_pred))

print("\nConfusion Matrix:")
print(metrics.confusion_matrix(y_test, x_test_pred))

Classification Report:
              precision    recall  f1-score   support

           0       0.90      1.00      0.95      3286
           1       0.86      0.05      0.10       366

    accuracy                           0.90      3652
   macro avg       0.88      0.53      0.52      3652
weighted avg       0.90      0.90      0.86      3652


Confusion Matrix:
[[3283    3]
 [ 347   19]]

In [39]:
# Calculate accuracy
accuracy = metrics.accuracy_score(y_test, x_test_pred)
print(f"Accuracy: {accuracy:.4f}")

Accuracy: 0.9042